AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack para la creación de instancias EC2 y RDS"

Parameters:
  KeyName:
    Type: String
    Description: "mensagl"

Resources:
  EC2ProxyAZ1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue agarciaa-SubnetPublic1-ID
      SecurityGroupIds:
        - !ImportValue agarciaa-SG-Proxy-AZ1-ID
      PrivateIpAddress: 10.209.1.50
      Tags:
        - Key: Name
          Value: "agarciaa-az1-proxy"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/EC2ProxyAZ1/ /tmp/
          sudo rm -r -f mensagl/

  EC2ProxyAZ2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue agarciaa-SubnetPublic2-ID
      SecurityGroupIds:
        - !ImportValue agarciaa-SG-Proxy-AZ2-ID
      PrivateIpAddress: 10.209.2.50
      Tags:
        - Key: Name
          Value: "agarciaa-az2-proxy"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/EC2ProxyAZ2/ /tmp/
          sudo rm -r -f mensagl/

  EC2Ejabberd1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue agarciaa-SubnetPrivate1-ID
      SecurityGroupIds:
        - !ImportValue agarciaa-SG-Ejabberd-ID
      PrivateIpAddress: 10.209.3.10
      Tags:
        - Key: Name
          Value: "agarciaa-ejabberd-1"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/EC2Ejabberd1/ /tmp/
          sudo rm -r -f mensagl/

  EC2Ejabberd2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue agarciaa-SubnetPrivate1-ID
      SecurityGroupIds:
        - !ImportValue agarciaa-SG-Ejabberd-ID
      PrivateIpAddress: 10.209.3.11
      Tags:
        - Key: Name
          Value: "agarciaa-ejabberd-2"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/EC2Ejabberd2/ /tmp/
          sudo rm -r -f mensagl/

  EC2PostgreSQL1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue agarciaa-SubnetPrivate1-ID
      SecurityGroupIds:
        - !ImportValue agarciaa-SG-PostgreSQL-ID
      PrivateIpAddress: 10.209.3.100
      Tags:
        - Key: Name
          Value: "agarciaa-az1-postgresql-1"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/EC2PostgreSQL1/ /tmp/
          sudo rm -r -f mensagl/

  EC2PostgreSQL2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue agarciaa-SubnetPrivate1-ID
      SecurityGroupIds:
        - !ImportValue agarciaa-SG-PostgreSQL-ID
      PrivateIpAddress: 10.209.3.101
      Tags:
        - Key: Name
          Value: "agarciaa-az1-postgresql-2"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/EC2PostgreSQL2/ /tmp/
          sudo rm -r -f mensagl/          

  EC2CMS1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue agarciaa-SubnetPrivate2-ID
      SecurityGroupIds:
        - !ImportValue agarciaa-SG-CMS-ID
        - !ImportValue agarciaa-SG-RDS-ID  # Asegura que CMS pueda hablar con RDS
      PrivateIpAddress: 10.209.4.10
      Tags:
        - Key: Name
          Value: "agarciaa-az2-cms1"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/EC2CMS1/ /tmp/
          sudo rm -r -f mensagl/

  EC2CMS2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue agarciaa-SubnetPrivate2-ID
      SecurityGroupIds:
        - !ImportValue agarciaa-SG-CMS-ID
        - !ImportValue agarciaa-SG-RDS-ID  # Asegura que CMS pueda hablar con RDS
      PrivateIpAddress: 10.209.4.11
      Tags:
        - Key: Name
          Value: "agarciaa-az2-cms2"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/EC2CMS2/ /tmp/
          sudo rm -r -f mensagl/


Outputs:
  EC2ProxyAZ1Id:
    Description: "ID de la instancia Proxy en AZ1"
    Value: !Ref EC2ProxyAZ1
    Export:
      Name: "agarciaa-EC2-Proxy-AZ1-ID"

  EC2ProxyAZ2Id:
    Description: "ID de la instancia Proxy en AZ2"
    Value: !Ref EC2ProxyAZ2
    Export:
      Name: "agarciaa-EC2-Proxy-AZ2-ID"

  EC2Ejabberd1Id:
    Description: "ID de la primera instancia Ejabberd"
    Value: !Ref EC2Ejabberd1
    Export:
      Name: "agarciaa-EC2-Ejabberd-1-ID"

  EC2Ejabberd2Id:
    Description: "ID de la segunda instancia Ejabberd"
    Value: !Ref EC2Ejabberd2
    Export:
      Name: "agarciaa-EC2-Ejabberd-2-ID"

  EC2PostgreSQL1Id:
    Description: "ID de la primera instancia PostgreSQL"
    Value: !Ref EC2PostgreSQL1
    Export:
      Name: "agarciaa-EC2-PostgreSQL-1-ID"

  EC2PostgreSQL2Id:
    Description: "ID de la segunda instancia PostgreSQL"
    Value: !Ref EC2PostgreSQL2
    Export:
      Name: "agarciaa-EC2-PostgreSQL-2-ID"

  EC2CMS1Id:
    Description: "ID de la primera instancia CMS"
    Value: !Ref EC2CMS1
    Export:
      Name: "agarciaa-EC2-CMS-1-ID"

  EC2CMS2Id:
    Description: "ID de la segunda instancia CMS"
    Value: !Ref EC2CMS2
    Export:
      Name: "agarciaa-EC2-CMS-2-ID"

